name: ci

on:
  push:
    branches:
      - master

jobs:
  all-tests:
    name: All Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'
        
      - name: Build with Maven
        run: ./mvnw verify
